using System.Text.RegularExpressions;

namespace TechHub.Infrastructure.Services;

/// <summary>
/// Fixes invalid JSON escape sequences generated by AI models (e.g. <c>\.</c>, <c>\-</c>).
/// JSON only allows <c>\" \\ \/ \b \f \n \r \t \uXXXX</c>.
/// Any other <c>\X</c> sequence is invalid — we drop the backslash and keep the character.
/// </summary>
internal static class JsonEscapeSanitizer
{
    internal static string SanitizeJsonEscapes(string json)
        => Regex.Replace(json, @"\\([^""\\\//bfnrtu])", "$1");
}
