using System.Text.RegularExpressions;

namespace TechHub.Infrastructure.Services;

/// <summary>
/// Fixes invalid JSON escape sequences generated by AI models (e.g. <c>\.</c>, <c>\-</c>, <c>\s</c>).
/// JSON only allows <c>\" \\ \/ \b \f \n \r \t \uXXXX</c>.
/// Any other <c>\X</c> sequence is invalid — we drop the backslash and keep the character.
/// </summary>
internal static class JsonEscapeSanitizer
{
    // Matches any backslash-prefixed sequence and either:
    //   1. \uXXXX   — valid Unicode escape   → keep as-is
    //   2. \"+one of "\/bfnrt  — valid single-char escape → keep as-is
    //   3. \X (anything else) — invalid escape, captured in group 2 → drop the backslash
    //
    // Using alternation ensures that \\ (valid escaped backslash) is fully consumed in
    // alternative 2, so the character after it is never incorrectly re-matched.
    // The previous simple regex \\([^"\\//bfnrtu]) failed for \\s: it would skip the
    // first \+\ match (second char excluded), then match the second \+s and strip it,
    // corrupting valid \\s into invalid \s.
    private static readonly Regex _invalidEscapeRegex =
        new(@"\\(u[0-9a-fA-F]{4}|[""\\/bfnrt]|([^""\\/bfnrtu]))",
            RegexOptions.Compiled);

    internal static string SanitizeJsonEscapes(string json)
        => _invalidEscapeRegex.Replace(json,
            m => m.Groups[2].Success ? m.Groups[2].Value : m.Value);
}
