using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TechHub.Core.Configuration;
using YoutubeExplode;
using YoutubeExplode.Exceptions;
using YoutubeExplode.Videos.ClosedCaptions;

using TechHub.Core.Interfaces;

namespace TechHub.Infrastructure.Services;

/// <summary>
/// Fetches YouTube video closed captions (transcripts) using YoutubeExplode.
/// Tries English captions first, then falls back to any auto-generated track.
/// Returns plain text transcript suitable for AI analysis. Failures are non-fatal
/// — the pipeline continues without transcript data if fetching fails.
/// </summary>
public class YouTubeTranscriptService : IYouTubeTranscriptService, IDisposable
{
    private readonly YoutubeClient _youtube;
    private readonly ContentProcessorOptions _options;
    private readonly ILogger<YouTubeTranscriptService> _logger;
    private bool _disposed;

    /// <summary>Maximum transcript length in characters to avoid overloading the AI prompt.</summary>
    private const int MaxTranscriptLength = 50_000;

    public YouTubeTranscriptService(
        IOptions<ContentProcessorOptions> options,
        ILogger<YouTubeTranscriptService> logger)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(logger);

        _youtube = new YoutubeClient();
        _options = options.Value;
        _logger = logger;
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!_disposed)
        {
            if (disposing)
            {
                (_youtube as IDisposable)?.Dispose();
            }

            _disposed = true;
        }
    }

    /// <summary>
    /// Fetches the transcript for <paramref name="videoUrl"/>.
    /// Returns <see langword="null"/> if no captions are available or on failure.
    /// </summary>
    public virtual async Task<string?> GetTranscriptAsync(string videoUrl, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(videoUrl);

        try
        {
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
            cts.CancelAfter(TimeSpan.FromSeconds(_options.RequestTimeoutSeconds));

            _logger.LogDebug("Fetching transcript for YouTube video: {Url}", videoUrl);

            var manifest = await _youtube.Videos.ClosedCaptions.GetManifestAsync(videoUrl, cts.Token);

            var trackInfo = FindBestTrack(manifest);
            if (trackInfo == null)
            {
                _logger.LogDebug("No suitable caption track found for {Url}", videoUrl);
                return null;
            }

            _logger.LogDebug("Using caption track: {Language} (auto={IsAutoGenerated}) for {Url}",
                trackInfo.Language.Name, trackInfo.IsAutoGenerated, videoUrl);

            var track = await _youtube.Videos.ClosedCaptions.GetAsync(trackInfo, cts.Token);

            var transcript = BuildTranscriptText(track);
            if (string.IsNullOrWhiteSpace(transcript))
            {
                return null;
            }

            _logger.LogInformation(
                "Fetched transcript for {Url}: {Length} chars from {Language} track",
                videoUrl, transcript.Length, trackInfo.Language.Name);

            return transcript;
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            throw;
        }
        catch (OperationCanceledException)
        {
            _logger.LogWarning("Timeout fetching transcript for {Url}", videoUrl);
            return null;
        }
        catch (Exception ex) when (ex is YoutubeExplodeException or HttpRequestException or IOException)
        {
            _logger.LogWarning(ex, "Failed to fetch transcript for {Url}", videoUrl);
            return null;
        }
    }

    /// <summary>
    /// Selects the best caption track: prefers English, then any language.
    /// Prefers non-auto-generated over auto-generated within the same language.
    /// </summary>
    internal static ClosedCaptionTrackInfo? FindBestTrack(ClosedCaptionManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);

        var tracks = manifest.Tracks;
        if (tracks.Count == 0)
        {
            return null;
        }

        // Prefer English (non-auto first, then auto-generated)
        var englishManual = tracks.FirstOrDefault(t =>
            t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase) && !t.IsAutoGenerated);
        if (englishManual != null)
        {
            return englishManual;
        }

        var englishAuto = tracks.FirstOrDefault(t =>
            t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase));
        if (englishAuto != null)
        {
            return englishAuto;
        }

        // Fall back to any non-auto track, then any auto track
        return tracks.FirstOrDefault(t => !t.IsAutoGenerated) ?? tracks[0];
    }

    private static string BuildTranscriptText(ClosedCaptionTrack track)
    {
        if (track.Captions.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var caption in track.Captions)
        {
            if (string.IsNullOrWhiteSpace(caption.Text))
            {
                continue;
            }

            sb.Append(caption.Text.Replace('\n', ' '));
            sb.Append(' ');

            if (sb.Length > MaxTranscriptLength)
            {
                break;
            }
        }

        return sb.ToString().Trim();
    }
}
