using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TechHub.Core.Configuration;
using TechHub.Core.Interfaces;
using TechHub.Core.Models.ContentProcessing;
using YoutubeExplode;
using YoutubeExplode.Exceptions;
using YoutubeExplode.Videos.ClosedCaptions;

namespace TechHub.Infrastructure.Services.ContentProcessing;

/// <summary>
/// Fetches YouTube video closed captions (transcripts) using YoutubeExplode.
/// Tries English captions first, then falls back to any auto-generated track.
/// Returns plain text transcript suitable for AI analysis. Failures are non-fatal
/// — the pipeline continues without transcript data if fetching fails.
/// </summary>
public class YouTubeTranscriptService : IYouTubeTranscriptService, IDisposable
{
    private readonly YoutubeClient _youtube;
    private readonly ContentProcessorOptions _options;
    private readonly ILogger<YouTubeTranscriptService> _logger;
    private bool _disposed;

    /// <summary>Maximum transcript length in characters to avoid overloading the AI prompt.</summary>
    private const int MaxTranscriptLength = 50_000;

    /// <summary>Maximum number of retry attempts for transient failures.</summary>
    private const int MaxRetryAttempts = 2;

    /// <summary>Base delay between retries (doubled each attempt).</summary>
    private static readonly TimeSpan _retryBaseDelay = TimeSpan.FromSeconds(2);

    public YouTubeTranscriptService(
        IOptions<ContentProcessorOptions> options,
        ILogger<YouTubeTranscriptService> logger)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(logger);

        _youtube = new YoutubeClient();
        _options = options.Value;
        _logger = logger;
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!_disposed)
        {
            if (disposing)
            {
                (_youtube as IDisposable)?.Dispose();
            }

            _disposed = true;
        }
    }

    /// <summary>
    /// Fetches the transcript for <paramref name="videoUrl"/>.
    /// Returns a <see cref="TranscriptResult"/> indicating success with text or failure with a reason.
    /// </summary>
    public virtual async Task<TranscriptResult> GetTranscriptAsync(string videoUrl, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(videoUrl);

        for (var attempt = 1; attempt <= MaxRetryAttempts + 1; attempt++)
        {
            try
            {
                using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                cts.CancelAfter(TimeSpan.FromSeconds(_options.RequestTimeoutSeconds));

                _logger.LogDebug("Fetching transcript for YouTube video: {Url} (attempt {Attempt})", videoUrl, attempt);

                var manifest = await _youtube.Videos.ClosedCaptions.GetManifestAsync(videoUrl, cts.Token);

                var trackInfo = FindBestTrack(manifest);
                if (trackInfo == null)
                {
                    _logger.LogInformation("No suitable caption track found for {Url}", videoUrl);
                    return TranscriptResult.Failure("No caption tracks available");
                }

                _logger.LogDebug("Using caption track: {Language} (auto={IsAutoGenerated}) for {Url}",
                    trackInfo.Language.Name, trackInfo.IsAutoGenerated, videoUrl);

                var track = await _youtube.Videos.ClosedCaptions.GetAsync(trackInfo, cts.Token);

                var transcript = BuildTranscriptText(track);
                if (string.IsNullOrWhiteSpace(transcript))
                {
                    return TranscriptResult.Failure("Caption track was empty");
                }

                _logger.LogInformation(
                    "Fetched transcript for {Url}: {Length} chars from {Language} track",
                    videoUrl, transcript.Length, trackInfo.Language.Name);

                return TranscriptResult.Success(transcript);
            }
            catch (OperationCanceledException) when (ct.IsCancellationRequested)
            {
                throw;
            }
            catch (VideoUnavailableException ex)
            {
                // Non-transient: video is private, removed, or region-restricted. No point retrying.
                _logger.LogWarning("Video unavailable for transcript: {Url} — {Message}", videoUrl, ex.Message);
                return TranscriptResult.Failure(ex.Message);
            }
            catch (VideoUnplayableException ex)
            {
                // Non-transient: video requires purchase or is age-restricted. No point retrying.
                _logger.LogWarning("Video unplayable for transcript: {Url} — {Message}", videoUrl, ex.Message);
                return TranscriptResult.Failure(ex.Message);
            }
            catch (Exception ex) when (ex is OperationCanceledException or HttpRequestException or IOException or YoutubeExplodeException)
            {
                if (attempt <= MaxRetryAttempts)
                {
                    var delay = _retryBaseDelay * (1 << (attempt - 1));
                    _logger.LogWarning(ex,
                        "Transcript fetch failed for {Url} (attempt {Attempt}/{Max}), retrying in {Delay}s",
                        videoUrl, attempt, MaxRetryAttempts + 1, delay.TotalSeconds);
                    await Task.Delay(delay, ct);
                }
                else
                {
                    _logger.LogWarning(ex, "Failed to fetch transcript for {Url} after {Attempts} attempts", videoUrl, attempt);
                    return TranscriptResult.Failure(ex.Message);
                }
            }
        }

        return TranscriptResult.Failure("Exhausted all retry attempts");
    }

    /// <summary>
    /// Selects the best caption track: prefers English, then any language.
    /// Prefers non-auto-generated over auto-generated within the same language.
    /// </summary>
    internal static ClosedCaptionTrackInfo? FindBestTrack(ClosedCaptionManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);

        var tracks = manifest.Tracks;
        if (tracks.Count == 0)
        {
            return null;
        }

        // Prefer English (non-auto first, then auto-generated)
        var englishManual = tracks.FirstOrDefault(t =>
            t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase) && !t.IsAutoGenerated);
        if (englishManual != null)
        {
            return englishManual;
        }

        var englishAuto = tracks.FirstOrDefault(t =>
            t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase));
        if (englishAuto != null)
        {
            return englishAuto;
        }

        // Fall back to any non-auto track, then any auto track
        return tracks.FirstOrDefault(t => !t.IsAutoGenerated) ?? tracks[0];
    }

    private static string BuildTranscriptText(ClosedCaptionTrack track)
    {
        if (track.Captions.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var caption in track.Captions)
        {
            if (string.IsNullOrWhiteSpace(caption.Text))
            {
                continue;
            }

            sb.Append(caption.Text.Replace('\n', ' '));
            sb.Append(' ');

            if (sb.Length > MaxTranscriptLength)
            {
                break;
            }
        }

        return sb.ToString().Trim();
    }
}
