using System.Net;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TechHub.Core.Configuration;
using TechHub.Core.Interfaces;
using TechHub.Core.Logging;
using TechHub.Core.Models.ContentProcessing;
using YoutubeExplode;
using YoutubeExplode.Exceptions;
using YoutubeExplode.Videos.ClosedCaptions;

namespace TechHub.Infrastructure.Services.ContentProcessing;

/// <summary>
/// Fetches YouTube video closed captions (transcripts).
/// Tries YoutubeExplode first (with configured HTTP client, browser UA, and cookies),
/// then falls back to yt-dlp if YoutubeExplode fails.
/// Returns plain text transcript suitable for AI analysis. Failures are non-fatal
/// - the pipeline continues without transcript data if fetching fails.
/// </summary>
public class YouTubeTranscriptService : IYouTubeTranscriptService, IDisposable
{
    private readonly YoutubeClient _youtube;
    private readonly YtDlpTranscriptService _ytDlp;
    private readonly ContentProcessorOptions _options;
    private readonly ILogger<YouTubeTranscriptService> _logger;
    private bool _disposed;

    /// <summary>Maximum transcript length in characters to avoid overloading the AI prompt.</summary>
    private const int MaxTranscriptLength = 50_000;

    /// <summary>Maximum number of retry attempts for transient failures.</summary>
    private const int MaxRetryAttempts = 2;

    /// <summary>Base delay between retries (doubled each attempt).</summary>
    private static readonly TimeSpan _retryBaseDelay = TimeSpan.FromSeconds(2);

    public YouTubeTranscriptService(
        HttpClient httpClient,
        YtDlpTranscriptService ytDlp,
        IOptions<ContentProcessorOptions> options,
        ILogger<YouTubeTranscriptService> logger)
    {
        ArgumentNullException.ThrowIfNull(httpClient);
        ArgumentNullException.ThrowIfNull(ytDlp);
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(logger);

        var cookies = ParseCookies(options.Value.YouTubeCookies);
        _youtube = cookies.Count > 0
            ? new YoutubeClient(httpClient, cookies)
            : new YoutubeClient(httpClient);
        _ytDlp = ytDlp;
        _options = options.Value;
        _logger = logger;

        if (cookies.Count > 0)
        {
            _logger.LogInformation("YouTubeTranscriptService configured with {Count} persistent cookie(s)", cookies.Count);
        }
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!_disposed)
        {
            if (disposing)
            {
                (_youtube as IDisposable)?.Dispose();
                _ytDlp.Dispose();
            }

            _disposed = true;
        }
    }

    /// <summary>
    /// Fetches the transcript for <paramref name="videoUrl"/>.
    /// Tries YoutubeExplode first (with configured HTTP client and cookies),
    /// then falls back to yt-dlp if YoutubeExplode fails.
    /// Returns a <see cref="TranscriptResult"/> indicating success with text or failure with a reason.
    /// </summary>
    public virtual async Task<TranscriptResult> GetTranscriptAsync(string videoUrl, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(videoUrl);

        // Use YoutubeExplode only (with browser UA + cookies)
        // yt-dlp fallback is disabled while we validate whether cookies are sufficient
        return await TryYoutubeExplodeAsync(videoUrl, ct);
    }

    /// <summary>
    /// Attempts to fetch a transcript using YoutubeExplode with retry logic.
    /// </summary>
    private async Task<TranscriptResult> TryYoutubeExplodeAsync(string videoUrl, CancellationToken ct)
    {
        for (var attempt = 1; attempt <= MaxRetryAttempts + 1; attempt++)
        {
            try
            {
                using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                cts.CancelAfter(TimeSpan.FromSeconds(_options.RequestTimeoutSeconds));

                _logger.LogDebug("Fetching transcript for YouTube video: {Url} (attempt {Attempt})", videoUrl, attempt);

                var manifest = await _youtube.Videos.ClosedCaptions.GetManifestAsync(videoUrl, cts.Token);

                var trackInfo = FindBestTrack(manifest);
                if (trackInfo == null)
                {
                    _logger.LogInformation("No suitable caption track found for {Url}", videoUrl);
                    return TranscriptResult.Failure("No caption tracks available");
                }

                _logger.LogDebug("Using caption track: {Language} (auto={IsAutoGenerated}) for {Url}",
                    trackInfo.Language.Name, trackInfo.IsAutoGenerated, videoUrl);

                var track = await _youtube.Videos.ClosedCaptions.GetAsync(trackInfo, cts.Token);

                var transcript = BuildTranscriptText(track);
                if (string.IsNullOrWhiteSpace(transcript))
                {
                    return TranscriptResult.Failure("Caption track was empty");
                }

                _logger.LogInformation(
                    "Fetched transcript for {Url}: {Length} chars from {Language} track",
                    videoUrl, transcript.Length, trackInfo.Language.Name);

                return TranscriptResult.Success(transcript);
            }
            catch (OperationCanceledException) when (ct.IsCancellationRequested)
            {
                throw;
            }
            catch (VideoUnavailableException ex)
            {
                _logger.LogWarning("Video unavailable for transcript: {Url} — {Message}", videoUrl.Sanitize(), ex.Message.Sanitize());
                return TranscriptResult.Failure(ex.Message);
            }
            catch (VideoUnplayableException ex)
            {
                _logger.LogWarning("Video unplayable for transcript: {Url} — {Message}", videoUrl.Sanitize(), ex.Message.Sanitize());
                return TranscriptResult.Failure(ex.Message);
            }
            catch (Exception ex) when (ex is OperationCanceledException or HttpRequestException or IOException or YoutubeExplodeException)
            {
                if (attempt <= MaxRetryAttempts)
                {
                    var delay = _retryBaseDelay * (1 << (attempt - 1));
                    _logger.LogWarning(ex,
                        "Transcript fetch failed for {Url} (attempt {Attempt}/{Max}), retrying in {Delay}s",
                        videoUrl, attempt, MaxRetryAttempts + 1, delay.TotalSeconds);
                    await Task.Delay(delay, ct);
                }
                else
                {
                    _logger.LogWarning(ex, "YoutubeExplode failed for {Url} after {Attempts} attempts", videoUrl, attempt);
                    return TranscriptResult.Failure(ex.Message);
                }
            }
        }

        return TranscriptResult.Failure("Exhausted all retry attempts");
    }

    /// <summary>
    /// Selects the best caption track: prefers English, then any language.
    /// Prefers non-auto-generated over auto-generated within the same language.
    /// </summary>
    internal static ClosedCaptionTrackInfo? FindBestTrack(ClosedCaptionManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);

        var tracks = manifest.Tracks;
        if (tracks.Count == 0)
        {
            return null;
        }

        // Prefer English (non-auto first, then auto-generated)
        var englishManual = tracks.FirstOrDefault(t =>
            t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase) && !t.IsAutoGenerated);
        if (englishManual != null)
        {
            return englishManual;
        }

        var englishAuto = tracks.FirstOrDefault(t =>
            t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase));
        if (englishAuto != null)
        {
            return englishAuto;
        }

        // Fall back to any non-auto track, then any auto track
        return tracks.FirstOrDefault(t => !t.IsAutoGenerated) ?? tracks[0];
    }

    private static string BuildTranscriptText(ClosedCaptionTrack track)
    {
        if (track.Captions.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var caption in track.Captions)
        {
            if (string.IsNullOrWhiteSpace(caption.Text))
            {
                continue;
            }

            sb.Append(caption.Text.Replace('\n', ' '));
            sb.Append(' ');

            if (sb.Length > MaxTranscriptLength)
            {
                break;
            }
        }

        return sb.ToString().Trim();
    }

    /// <summary>
    /// Parses a semicolon-delimited cookie string (e.g. "PREF=value;VISITOR_PRIVACY_METADATA=value")
    /// into <see cref="Cookie"/> objects scoped to .youtube.com domain.
    /// </summary>
    internal static List<Cookie> ParseCookies(string cookieString)
    {
        var cookies = new List<Cookie>();
        if (string.IsNullOrWhiteSpace(cookieString))
        {
            return cookies;
        }

        foreach (var entry in cookieString.Split(';'))
        {
            if (string.IsNullOrWhiteSpace(entry))
            {
                continue;
            }

            var separatorIndex = entry.IndexOf('=', StringComparison.Ordinal);
            if (separatorIndex <= 0)
            {
                continue;
            }

            var name = entry[..separatorIndex].Trim();
            var value = entry[(separatorIndex + 1)..].Trim();

            cookies.Add(new Cookie(name, value, "/", ".youtube.com"));
        }

        return cookies;
    }
}
